name: 'minify-action'
description: 'Combine and Minify css and js deployment.'
author: "datatory.io / Taco de Wolff"

inputs:
  css_dir:
    description: "the dir containing all css files"
    required: false
  css_files:
    description: "files seperated by space to process (* for all)"
    required: false
  output_css: 
    description: "output file or dir for the css files"
    required: false
  js_dir:
    description: "the dir containing all js files"
    required: false
  js_files:
    description: "files seperated by space to process (* for all)"
    required: false
  output_js:
    description: "output file or dir for the css files"
    required: false
  

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: "box"
  color: "blue"
